// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhmrGz0RZhfiOE4U7b7h8WJZy_9G8bpRE',
    appId: '1:768824296253:web:7bab5195234c452765bb54',
    messagingSenderId: '768824296253',
    projectId: 'reddit-clone-b2a34',
    authDomain: 'reddit-clone-b2a34.firebaseapp.com',
    storageBucket: 'reddit-clone-b2a34.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbUU0xnNLMYuDPZ2tLtfWJCIozx-rrorw',
    appId: '1:768824296253:android:3e82936c9520b5a065bb54',
    messagingSenderId: '768824296253',
    projectId: 'reddit-clone-b2a34',
    storageBucket: 'reddit-clone-b2a34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnRWNAMXh5kPVCldHny4IRgxXpgMv2gjk',
    appId: '1:768824296253:ios:703b8b39fca9598f65bb54',
    messagingSenderId: '768824296253',
    projectId: 'reddit-clone-b2a34',
    storageBucket: 'reddit-clone-b2a34.appspot.com',
    iosClientId: '768824296253-ien8v550l9br0m5ri0jlhet6epmf2i9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditCloneRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnRWNAMXh5kPVCldHny4IRgxXpgMv2gjk',
    appId: '1:768824296253:ios:703b8b39fca9598f65bb54',
    messagingSenderId: '768824296253',
    projectId: 'reddit-clone-b2a34',
    storageBucket: 'reddit-clone-b2a34.appspot.com',
    iosClientId: '768824296253-ien8v550l9br0m5ri0jlhet6epmf2i9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditCloneRiverpod',
  );
}
